services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
  node-backend:
    build: .
    depends_on: [ db ]
    ports:
      - '3000:3000'
volumes:
  dbdata:
